config/routes.rb
RcEnrollmentSystem::Application.routes.draw do

  resources :autoscoring_project_scoring_jobs do
    member do
      get 'process_file'
      get 'queued_process_file'
      get 'download_current_input_file'
      get 'create_dbf_file'
      get 'create_output_csv_file'
      get 'download_dbf_file'
      get 'download_csv_input_file'
      get 'download_csv_output_file'
      get 'enqueue_file_on_resque'
      get 'enqueue_file_on_sidekiq'
      get 'preview_email'
      get 'delete_scoring_job_records'
    end
  end

  resources :postal_codes do
    collection do
      get 'autocomplete_search'
    end
  end

  resources :job_titles

  resources :autoscoring_project_other_variables

  resources :autoscoring_project_other_variable_count_imports

  resources :autoscoring_project_geodemographic_variable_count_imports

  resources :autoscoring_projects

  resources :institutions

  resources :file_imports do
    member do
      get 'test_import'
      get 'import'
      get 'download'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :admin_users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  root :to => 'home#index'

  authenticate :admin_user do
    mount Resque::Server.new, :at => "/resque"
  end

  authenticate :admin_user do
    mount Sidekiq::Web.new, at: '/sidekiq'
  end

end

app/models/autoscoring_project_geodemographic_variable_count_import.rb
class AutoscoringProjectGeodemographicVariableCountImport
  # switch to ActiveModel::Model in Rails 4
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :file, :autoscoring_project_geodemographic_variable_id, :delete_existing_records

  validates :file, :presence => true
  validates :autoscoring_project_geodemographic_variable_id, :presence => true
  validates :delete_existing_records, :presence => true

  def initialize(attributes = {})
    attributes.each { |name, value| send("#{name}=", value) }
  end

  def delete_existing_records?
    !!@delete_existing_records
  end

  def persisted?
    false
  end

  def save

    begin
      ActiveRecord::Base.transaction do
        if self.delete_existing_records.to_bool
          AutoscoringProjectGeodemographicVariableCount.delete_all(["autoscoring_project_geodemographic_variable_id = ?", self.autoscoring_project_geodemographic_variable_id])
          autoscoring_project_geodemographic_variable = AutoscoringProjectGeodemographicVariable.find(self.autoscoring_project_geodemographic_variable_id)
          autoscoring_project_geodemographic_variable.update_attributes(:has_uploaded_counts => false)
        end

        if imported_counts.map(&:valid?).all?

          #imported_counts.each(&:save!)
          AutoscoringProjectGeodemographicVariableCount.import imported_counts

          true
        else
          imported_counts.each_with_index do |count, index|
            count.errors.full_messages.each do |message|
              errors.add :base, "Row #{index+2}: #{message}"
            end
          end
          false
        end

      end
    end

  end

  def imported_counts
    @imported_counts ||= load_imported_counts
  end

  def load_imported_counts
    spreadsheet = open_spreadsheet
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).map do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      count = AutoscoringProjectGeodemographicVariableCount.find_by_autoscoring_project_geodemographic_variable_id_and_name(self.autoscoring_project_geodemographic_variable_id, row["Code"])
      if count.nil? then
        count = AutoscoringProjectGeodemographicVariableCount.new
        count.autoscoring_project_geodemographic_variable_id = self.autoscoring_project_geodemographic_variable_id
        count.name = t_description = row["Code"]
        count.enrolled = row["Enrolled"]
        count.total = row["Total"]
        count
      else
        count.enrolled = row["Enrolled"]
        count.total = row["Total"]
        count
      end
    end
  end

  def open_spreadsheet
    case File.extname(file.original_filename).downcase
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/views/admin/autoscoring_project_geodemographic_variable_count_imports/_form.html.erb
<h1><%= link_to @autoscoring_project_geodemographic_variable.autoscoring_project.name, admin_autoscoring_project_path(@autoscoring_project_geodemographic_variable.autoscoring_project)%> </h1>
<h1><%= @autoscoring_project_geodemographic_variable.variable.name %> Variable Counts Import</h1>

<p>A CSV or Excel file can be used to import records. The first row should be the column name. The following columns are required.</p>

<ul>
    <li>
      <strong>Code (e.g., 1HVL - 5HVL)</strong> - String Type
    </li>
    <li>
      <strong>Enrolled</strong> - Integer type
    </li>
    <li>
     <strong>Total</strong> - Integer type
    </li>
</ul>

<%= semantic_form_for [:admin, @autoscoring_project_geodemographic_variable_count_import] do |f| %>
	<% #f.semantic_errors :autoscoring_project_geodemographic_variable_translation_import %>
	<% if @autoscoring_project_geodemographic_variable_count_import.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@autoscoring_project_geodemographic_variable_count_import.errors.count, "error") %> prohibited this import from completing:</h2>
    <ul>
    <% @autoscoring_project_geodemographic_variable_count_import.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
	<%= f.inputs "File" do %>
   		<%= f.input :file, :as => :file, :label => true %>
		<% if @autoscoring_project_geodemographic_variable.has_uploaded_counts? %>
			<%= f.input :delete_existing_records, :as => :boolean, :label => "Delete Existing Records" %>
		<% else %>
			<%= f.input :delete_existing_records, :as => :hidden, :value => false , :label => false %>
		<% end %>
		<%= f.input :autoscoring_project_geodemographic_variable_id, :as => :hidden, :value =>  @autoscoring_project_geodemographic_variable.id %>
	<% end %>
	<%= f.actions do %>
  		<%= f.action :submit,  :label => "Import" %>
	<% end %>
<% end %>

<hr />

<% if @autoscoring_project_geodemographic_variable.has_uploaded_counts? %>
<h1><%= @autoscoring_project_geodemographic_variable.variable.name %> Variable Current Counts (n= <%= @autoscoring_project_geodemographic_variable_counts.count %>)</h1>
<div>
	<ul>
		<% @autoscoring_project_geodemographic_variable_counts.each do |count| %>
			<li><strong><%= count.name %></strong> (<%= count.enrolled %> / <%= count.total.to_s %>) - <%= number_to_percentage(count.yield_as_percentage, :precision => 6) %></li>
		<% end %>
	</ul>
</div>
<% else %>
<h1>No Variable Current Counts (n= 0)</h1>
<% end %>