config/routes.rb
RcEnrollmentSystem::Application.routes.draw do

  resources :autoscoring_project_scoring_jobs do
    member do
      get 'process_file'
      get 'queued_process_file'
      get 'download_current_input_file'
      get 'create_dbf_file'
      get 'create_output_csv_file'
      get 'download_dbf_file'
      get 'download_csv_input_file'
      get 'download_csv_output_file'
      get 'enqueue_file_on_resque'
      get 'enqueue_file_on_sidekiq'
      get 'preview_email'
      get 'delete_scoring_job_records'
    end
  end

  resources :postal_codes do
    collection do
      get 'autocomplete_search'
    end
  end

  resources :job_titles

  resources :autoscoring_project_other_variables

  resources :autoscoring_project_other_variable_count_imports

  resources :autoscoring_project_geodemographic_variable_count_imports

  resources :autoscoring_projects

  resources :institutions

  resources :file_imports do
    member do
      get 'test_import'
      get 'import'
      get 'download'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :admin_users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  root :to => 'home#index'

  authenticate :admin_user do
    mount Resque::Server.new, :at => "/resque"
  end

  authenticate :admin_user do
    mount Sidekiq::Web.new, at: '/sidekiq'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    if current_user.is_administrator?
      @available_em_configured_autoscoring_projects = AutoscoringProject.includes(:autoscoring_project_scoring_jobs, :institution).select("institutions.name, autoscoring_projects.name").where('autoscoring_projects.active = true AND autoscoring_projects.autoscoring_project_status_id  IN (?) AND autoscoring_projects.is_em_configured = true', [2,3]).order('institutions.name ASC')
      @available_client_configured_autoscoring_projects = AutoscoringProject.includes(:autoscoring_project_scoring_jobs, :institution).select("institutions.name, autoscoring_projects.name").where('autoscoring_projects.active = true AND autoscoring_projects.autoscoring_project_status_id  IN (?) AND autoscoring_projects.is_em_configured = false', [2,3]).order('institutions.name ASC')
    else
      @current_users_available_recent_scoring_jobs = AutoscoringProjectScoringJob.includes(:autoscoring_project, :autoscoring_project_job_status).where('autoscoring_project_scoring_jobs.user_id = ? AND autoscoring_projects.active = true  AND autoscoring_projects.autoscoring_project_status_id = 3', current_user.id).order('autoscoring_project_scoring_jobs.updated_at DESC').limit(5)
      @available_em_configured_autoscoring_projects = AutoscoringProject.includes(:autoscoring_project_scoring_jobs, :institution).select("institutions.name, autoscoring_projects.name").where('autoscoring_projects.active = true AND autoscoring_projects.autoscoring_project_status_id = ? AND autoscoring_projects.is_em_configured = true', 3).order('institutions.name ASC')
      @available_client_configured_autoscoring_projects = AutoscoringProject.includes(:autoscoring_project_scoring_jobs, :institution).select("institutions.name, autoscoring_projects.name").where('autoscoring_projects.active = true AND autoscoring_projects.autoscoring_project_status_id = ? AND autoscoring_projects.is_em_configured = false', 3).order('institutions.name ASC')

    end
  end
end

app/views/home/index.html.erb
<div class="row-fluid">
	<div class="span10">
		<h1 class="text-center">RuffaloCODY Inquiry to Enroll Auto-Scoring System</h1>
	</div>
</div>
<hr />
<br />

<div class="row-fluid">
	<div class="span10">
	    <h2 class="text-center">Your Most Recent Scoring Jobs For Available Auto-Scoring Projects</h3>
	</div>
	<div class="span10">
		<table class="table table-hover">
			<thead>
			<tr>
				<th>Scoring Job ID</th>
				<th>Status</th>
				<th># of Completed Scoring Jobs</th>
				<th>Rows Processed</th>
				<th>Updated At</th>
				<th></th>
			</tr>
			</thead>
			<tbody>
			<% if @current_users_available_recent_scoring_jobs.nil? %>
			<tr>
				<td colspan="5"><div class="text-center">No Past Scoring Jobs for Available Auto-Scoring Projects Created by You</div></td>
			</tr>
			<% else %>
				<% @current_users_available_recent_scoring_jobs.each do |autoscoring_project_scoring_job| %>
					<tr>
						<td><%= autoscoring_project_scoring_job.id %></td>
						<td><%= autoscoring_project_scoring_job.autoscoring_project_job_status.name %></td>
						<td><%= autoscoring_project_scoring_job.autoscoring_project.name_with_configuration %></td>
						<td><%= autoscoring_project_scoring_job.rows_processed %></td>
						<td><%= autoscoring_project_scoring_job.updated_at.strftime("%m/%d/%y %I:%M %p %Z") %></td>
						<td><%= link_to ' <i class="icon-info-sign""></i> Summary Details '.html_safe, autoscoring_project_scoring_job_path(autoscoring_project_scoring_job.id), :class=> "btn btn-success " %></td>
					</tr>
					
				<% end %>			
			<% end %>
			</tbody>
		</table>
	</div>
</div>
<div class="row-fluid">
	<div class="span10">
	    <h2 class="text-center">Available Auto-Scoring Projects</h3>
	</div>
</div>

<div class="row-fluid">
	<div class="span10 tabbable">
		<ul class="nav nav-pills">
		  <li class="active">
		    <a href="#em-configured-projects" data-toggle="tab">Enrollment Manager Configured Projects</a>
		  </li>
		  <li><a href="#client-configured-projects" data-toggle="tab">Client Configured Projects</a></li>
		</ul>
	</div>
</div>

<div class="row-fluid">
	<div class="tab-content">
		<div id="em-configured-projects" class="tab-pane active">
			<div class="row-fluid">
				<div class="span10">
					<h3 class="text-center">Enrollment Manager Format Configured Auto-Scoring Projects</h3>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span10">
					<table class="table table-hover">
						<thead>
						<tr>
							<th>Institution</th>
							<th>Institution's Current Model Project</th>
							<th># of Completed Scoring Jobs</th>
							<th></th>
							<th></th>
						</tr>
						</thead>
						<tbody>
							<% if @available_em_configured_autoscoring_projects.nil? %>
								<tr>
									<td colspan="5"><div class="text-center">No EM Configured Auto-Scoring Projects Available</div></td>
								</tr>
							<% else %>
								<% @available_em_configured_autoscoring_projects.each do |available_em_autoscoring_project| %>
									<tr>
										<td><%= available_em_autoscoring_project.institution.name %></td>
										<td><%= available_em_autoscoring_project.name %>
										<td><%= available_em_autoscoring_project.public_autoscoring_project_scoring_job_count.to_s %></td>
										<td><%= link_to "Create New Scoring Job", new_autoscoring_project_scoring_job_path(:autoscoring_project_id => available_em_autoscoring_project.id), :class=> "btn btn-primary " if available_em_autoscoring_project.can_accept_new_scoring_job? %></td>
										<td><%= link_to ' <i class="icon-info-sign""></i> Details '.html_safe, available_em_autoscoring_project, :class=> "btn btn-success btn-block" %></td>
									</tr>
								<% end %>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div id="client-configured-projects"  class="tab-pane">
			<div class="row-fluid">
				<div class="span10">
					<h3 class="text-center">Client Format Configured Auto-Scoring Projects</h3>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span10">
					<table class="table table-hover">
						<thead>
						<tr>
							<th>Institution</th>
							<th>Institution's Current Model Project</th>
							<th># of Completed Scoring Jobs</th>
							<th></th>
							<th></th>
						</tr>
						</thead>
						<tbody>
							<% if @available_client_configured_autoscoring_projects.nil? %>
								<tr>
									<td colspan="5"><div class="text-center">No Client Configured Auto-Scoring Projects Available</div></td>
								</tr>
							<% else %>
								<% @available_client_configured_autoscoring_projects.each do |available_client_autoscoring_project| %>
									<tr>
										<td><%= available_client_autoscoring_project.institution.name %><%= " - (Only Available to Admin Users)" if !available_client_autoscoring_project.is_public? %></td>
										<td><%= available_client_autoscoring_project.name %>
										<td><%= available_client_autoscoring_project.public_autoscoring_project_scoring_job_count.to_s %></td>
										<td><%= link_to "Create New Scoring Job", new_autoscoring_project_scoring_job_path(:autoscoring_project_id => available_client_autoscoring_project.id), :class=> "btn btn-primary " if available_client_autoscoring_project.can_accept_new_scoring_job? %></td>
										<td><%= link_to ' <i class="icon-info-sign""></i> Details '.html_safe, available_client_autoscoring_project, :class=> "btn btn-success btn-block" %></td>
									</tr>
								<% end %>
						<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>