config/routes.rb
RcEnrollmentSystem::Application.routes.draw do

  resources :autoscoring_project_scoring_jobs do
    member do
      get 'process_file'
      get 'queued_process_file'
      get 'download_current_input_file'
      get 'create_dbf_file'
      get 'create_output_csv_file'
      get 'download_dbf_file'
      get 'download_csv_input_file'
      get 'download_csv_output_file'
      get 'enqueue_file_on_resque'
      get 'enqueue_file_on_sidekiq'
      get 'preview_email'
      get 'delete_scoring_job_records'
    end
  end

  resources :postal_codes do
    collection do
      get 'autocomplete_search'
    end
  end

  resources :job_titles

  resources :autoscoring_project_other_variables

  resources :autoscoring_project_other_variable_count_imports

  resources :autoscoring_project_geodemographic_variable_count_imports

  resources :autoscoring_projects

  resources :institutions

  resources :file_imports do
    member do
      get 'test_import'
      get 'import'
      get 'download'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :admin_users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  root :to => 'home#index'

  authenticate :admin_user do
    mount Resque::Server.new, :at => "/resque"
  end

  authenticate :admin_user do
    mount Sidekiq::Web.new, at: '/sidekiq'
  end

end

app/controllers/autoscoring_project_scoring_jobs_controller.rb
class AutoscoringProjectScoringJobsController < ApplicationController
  before_filter :authenticate_any_user!
  before_filter :check_autoscoring_project_availibility
  
  
  def index
    @autoscoring_project_scoring_jobs = AutoscoringProjectScoringJob.all

  end

  def show
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.includes(:user, :autoscoring_project_scoring_job_input_files,:autoscoring_project_scoring_job_output_files, :autoscoring_project => [:autoscoring_project_geodemographic_variables => [:variable], :autoscoring_project_other_variables => [:variable]]).find(params[:id])
    @autoscoring_project_scoring_job_log = @autoscoring_project_scoring_job.last_autoscoring_project_scoring_job_log
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.new
    respond_to do |format|
      if params[:autoscoring_project_id]
        @autoscoring_project = AutoscoringProject.find(params[:autoscoring_project_id])
        1.times { @autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_files.build }
        @user = current_user
        format.html # new.html.erb
      else
        format.html { redirect_to root_path }
      end
    end
  end

  # GET /autoscoring_project_scoring_jobs/1/edit
  def edit
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])
    @autoscoring_project = @autoscoring_project_scoring_job.autoscoring_project
    1.times { @autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_files.build }
    @user = @autoscoring_project_scoring_job.user
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # POST /autoscoring_project_scoring_jobs
  def create
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.new(params[:autoscoring_project_scoring_job])
    @autoscoring_project = @autoscoring_project_scoring_job.autoscoring_project
    @autoscoring_project_scoring_job.autoscoring_project_job_status_id = 1 # Not Started Processing
    respond_to do |format|
      if @autoscoring_project_scoring_job.save
        @autoscoring_project_scoring_job.update_column(:autoscoring_project_job_status_id, 5) # Queued up for Processing
        if ScoringJobWorker.perform_async(@autoscoring_project_scoring_job.id)
          #queued up successfully
        else
          @autoscoring_project_scoring_job.update_column(:autoscoring_project_job_status_id, 1) # Not Started Processing
        end
        sleep(2)
        # ScoringJobsWorker.perform_async(@autoscoring_project_scoring_job.id)
        format.html { redirect_to( @autoscoring_project_scoring_job.autoscoring_project, :notice => 'Scoring Job was Created Successfully & placed in the Scoring Queue.') }
      else
        @user = current_user
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /autoscoring_project_scoring_jobs/1
  def update
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])
    @autoscoring_project = @autoscoring_project_scoring_job.autoscoring_project
    params[:autoscoring_project_scoring_job][:has_file_dimension_counts] = false
    params[:autoscoring_project_scoring_job][:autoscoring_project_job_status_id] = 1 # Not Started Processing


    respond_to do |format|
      if @autoscoring_project_scoring_job.update_attributes(params[:autoscoring_project_scoring_job])
        @autoscoring_project_scoring_job.update_column(:autoscoring_project_job_status_id, 5) # Queued up for Processing
        if ScoringJobWorker.perform_async(@autoscoring_project_scoring_job.id)
          #queued up successfully
        else
          @autoscoring_project_scoring_job.update_column(:autoscoring_project_job_status_id, 1) # Not Started Processing
        end
        sleep(2)
        # format.html { redirect_to(@autoscoring_project_scoring_job.autoscoring_project, :anchor => "scoring-jobs-list", :notice => 'Scoring Job Input File was successfully updated.') }
        format.html { redirect_to( @autoscoring_project_scoring_job.autoscoring_project, :notice => 'Scoring Job was Created Updated & placed in the Scoring Queue.') }
      else
        @user = @autoscoring_project_scoring_job.user
        format.html { render :action => "edit" }
      end
    end
  end

  def delete_scoring_job_records
    authenticate_admin_user!
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])
    # delete scoring job records
    @autoscoring_project_scoring_job.delete_all_scoring_job_records
    respond_to do |format|
      format.html { redirect_to( [:admin,@autoscoring_project_scoring_job], :notice => 'Scoring Job Record Deletion Process Initiated for this Scoring Job.') }
    end
  end

  def download_current_input_file
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])

    input_file = @autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_file.file_name

    # Store the file locally in the tmp file, Cronjob will clean it up later on
    input_file.retrieve_from_store!(File.basename(input_file.url))
    input_file.cache_stored_file!
    @autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_file if send_file input_file.file.path, :disposition => 'attachment'

  rescue ActiveRecord::RecordNotFound
    redirect_to( @autoscoring_project_scoring_job, :alert => 'Requested CSV File Not Found on Server. Please contact the Admin for assistance.')

    # send_file @autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_file.file_name.to_s, :disposition => 'attachment'
    # rescue ActiveRecord::RecordNotFound
    #   logger.warn("#{Time.now} - Requested File Not Found: #{params.inspect}")
    #   render :text => t('private_files_controller.not_found'), :status => 404
  end

  def create_dbf_file
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])

    respond_to do |format|
      if @autoscoring_project_scoring_job.create_dbf_file
        format.html { redirect_to( @autoscoring_project_scoring_job, :notice => 'Scoring DBF was successfully created.') }
      else
        format.html { redirect_to( @autoscoring_project_scoring_job, :alert => 'Error Creating DBF(s) for Scoring Job') }
      end
    end
  end


  def create_output_csv_file
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])

    respond_to do |format|
      if @autoscoring_project_scoring_job.create_scored_csv_output_file
        format.html { redirect_to( @autoscoring_project_scoring_job, :notice => 'Scoring CSV was successfully created.') }
      else
        format.html { redirect_to( @autoscoring_project_scoring_job, :alert => 'Error Creating CSV(s) for Scoring Job') }
      end
    end
  end

  def download_dbf_file
    @autoscoring_project_scoring_job_output_file = AutoscoringProjectScoringJobOutputFile.find(params[:id])
    scored_file = @autoscoring_project_scoring_job_output_file.file_name
    scored_file.retrieve_from_store!(File.basename(scored_file.url))
    scored_file.cache_stored_file!
    send_file scored_file.file.path, :disposition => 'attachment'
  rescue ActiveRecord::RecordNotFound
    redirect_to( @autoscoring_project_scoring_job_output_file.autoscoring_project_scoring_job, :alert => 'Requested DBF File Not Found on Server. Please contact the Admin for assistance.')
  end
  
  def download_csv_input_file
    debugger
      @autoscoring_project_scoring_job_input_file = AutoscoringProjectScoringJobInputFile.find(params[:input_file_id])
      input_file = @autoscoring_project_scoring_job_input_file.file_name

      # Store the file locally in the tmp file, Cronjob will clean it up later on
      input_file.retrieve_from_store!(File.basename(input_file.url))
      input_file.cache_stored_file!
      send_file input_file.file.path, :disposition => 'attachment'
    rescue ActiveRecord::RecordNotFound
      redirect_to( @autoscoring_project_scoring_job_input_file.autoscoring_project_scoring_job, :alert => 'Requested CSV File Not Found on Server. Please contact the Admin for assistance.')
    end

  def download_csv_output_file
    @autoscoring_project_scoring_job_output_file = AutoscoringProjectScoringJobOutputFile.find(params[:output_file_id])
    scored_file = @autoscoring_project_scoring_job_output_file.file_name

    # Store the file locally in the tmp file, Cronjob will clean it up later on
    scored_file.retrieve_from_store!(File.basename(scored_file.url))
    scored_file.cache_stored_file!
    send_file scored_file.file.path, :disposition => 'attachment'
  rescue ActiveRecord::RecordNotFound
    redirect_to( @autoscoring_project_scoring_job_output_file.autoscoring_project_scoring_job, :alert => 'Requested CSV File Not Found on Server. Please contact the Admin for assistance.')
  end

  # Resque Version
  def enqueue_file_on_resque
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])
    @autoscoring_project_scoring_job.autoscoring_project_job_status_id = 1 # Queued

    respond_to do |format|
      if @autoscoring_project_scoring_job.save
        if Resque.enqueue(ScoringJobProcessor, @autoscoring_project_scoring_job.id)
          @autoscoring_project_scoring_job.update_attributes(:autoscoring_project_job_status_id => 5) # Queued up for Processing
        end
        format.html { redirect_to( @autoscoring_project_scoring_job, :notice => 'Scoring Job was Created Updated & placed in the Scoring Queue.') }
      else
        format.html { render :action => "show" }
      end
    end
  end


  #Sidekiq Version
  def enqueue_file_on_sidekiq
    @autoscoring_project_scoring_job = AutoscoringProjectScoringJob.find(params[:id])
    @autoscoring_project_scoring_job.autoscoring_project_job_status_id = 1 # Queued

    respond_to do |format|
      if @autoscoring_project_scoring_job.save

app/views/autoscoring_project_scoring_jobs/_form.html.erb
<div class="row-fluid">
	<div class="span10">
		<%= semantic_form_for(@autoscoring_project_scoring_job) do |f| %>
		<%= f.semantic_errors %>	
		<%= f.inputs do %>	
			<div class="well well-small">
				The Auto-Score System requires that the file to be scored represents an entire cohort(s) of students. The reason we need the entire inquiry pool is because the A-J ranks &amp; percentile scores are relative measures meaning it's value is relative to the group of records processed. These A-J ranks &amp; percentile scores should always be interpreted within the context of the entire inquiry pool. Any records scored outside the context of the entire inquiry pool results in skewed, inaccurate scoring results therefore we require you to include entire inquiry pool(s) in every scoring.
			</div>
			<br />
			<%= f.input :cohort_year, :prompt => "No Individual Cohort Year Specified", :label => false, :collection => Year.first(3) %>
		  	<%= f.semantic_fields_for :autoscoring_project_scoring_job_input_files do |f| %>
				<% if f.object.new_record? %>
				<br />
				<li>
					<%= f.input :file_name, :as => :file, :hint => "Note: System Only Accepts UTF-8 Encoded CSV Files.", :label => false %><%= f.input :file_import_type_id, :as => :hidden, :value => 2 %>
				</li>
				<% end %>
			<% end %>
			<br />
			<%= f.input :details, :placeholder => "Please provide details about this scoring job (Required)",  :label => false, :input_html => { :class => 'autogrow', :rows => 20, :columns => 50 }  %>
			
			<%= f.input :user_id, :as => :hidden, :value => @user.id %>
			<%= f.input :autoscoring_project_job_status_id, :as => :hidden, :value => 1 %>
			<% if current_user.is_administrator? then %>
				<%= f.input :is_test_scoring, :label => " Is Test Scoring (Only visible to Administrator Users & Not General Users)", :input_html => { :checked => true }  %>
				<%= f.input :is_public, :label => " Is Public", :input_html => { :checked => 0 }  %>
			<% else %>
				<%= f.input :is_test_scoring, :as => :hidden, :input_html => { :value => 0 }  %>
				<%= f.input :is_public, :as => :hidden, :input_html => { :value => 1 }  %>
			<% end %>
			<%= f.input :autoscoring_project_id, :as => :hidden, :value => @autoscoring_project.id %>

		<% end %>
		<br/>
		
		<button id="submit" type="submit" class="btn btn-large btn-block btn-primary" data-confirm="Does the selected file represent the client's entire inquiry pool(s) for the included entry term's cohort of students?" data-disable-with="Uploading, please wait...">
		  <i class="icon-refresh "></i> Upload To Queue
		</button>
		<% end %>
	</div>
</div>

app/views/autoscoring_project_scoring_jobs/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><%= link_to @autoscoring_project_scoring_job.autoscoring_project.name, @autoscoring_project_scoring_job.autoscoring_project  %><span class="divider">/</span></li>
  <li class="active">Update Current Scoring Job</li>
</ul>

<h1>Update Current Scoring Job's Input File</h1>

<%= render 'form' %>

app/views/autoscoring_project_scoring_jobs/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><%= link_to @autoscoring_project.name, @autoscoring_project  %><span class="divider">/</span></li>
  <li class="active">New Scoring Job</li>
</ul>

<h1>Create a New Scoring Job for <%=  @autoscoring_project.name %></h1>

<%= render 'form' %>

app/views/autoscoring_project_scoring_jobs/show.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><%= link_to @autoscoring_project_scoring_job.autoscoring_project.name, @autoscoring_project_scoring_job.autoscoring_project  %><span class="divider">/</span></li>
  <li class="active">Current Scoring Job</li>
</ul>

<div class="row-fluid">
	<div class="span8">
		<h2>Current Auto-Scoring Job's Summary for <%= @autoscoring_project_scoring_job.autoscoring_project.name %></h2>
	</div>
	<div class="span2">
	</div>
</div>

<div class="row-fluid">
	<div class="span10">
		<% if @autoscoring_project_scoring_job.not_started? %>
		<div class="alert alert-block alert-primary">
		  <h4><i class="icon-search icon-asterisk"></i> Scoring Job Scoring Job Process Has Not Started</h4>
		</div>
		<% elsif @autoscoring_project_scoring_job.in_queue? %>
		<div class="alert alert-block alert-info">
		  <h4><i class="icon-search icon-asterisk"></i> Scoring Job Successfully Placed In Queue. Waiting For Processing</h4>
		</div>
		<% elsif @autoscoring_project_scoring_job.in_progress? %>
			<div class="alert alert-block alert-warning">
			  <h4><i class="icon-search icon-exclamation-sign"></i> Currently Processing Scoring Job...</h4> 
			</div>
			
		<% elsif @autoscoring_project_scoring_job.completed? %>
		<div class="alert alert-block alert-success">
		  <h4><i class="icon-search icon-ok"></i> Scoring Job Processed &amp; Completed Successfully!</h4> 
		</div>
		<% elsif @autoscoring_project_scoring_job.encountered_errors? %>
			<div class="alert alert-block alert-error">
			  <h4><i class="icon-search icon-remove"></i> Error Occurred during Scoring Job Processing!</h4>
			  Please see the Error Details below to fix the input file and upload a revised version.
			</div>
		<% else%>
			none
		<% end %>

	</div>
</div>

<% if  @autoscoring_project_scoring_job.in_queue? || @autoscoring_project_scoring_job.in_progress? %>
<div class="row-fluid">
	<div class="span10">
		<p>Currently still processing this Scoring Job's file named "<% File.basename(@autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_file.file_name.path) %>"
		</p>
		<p>Please check back later to see this Scoring Job is finished. When the Scoring Job has finished processing, we will send the Scoring Job's Summary email to <strong><%= @autoscoring_project_scoring_job.user.email %></strong>. </p>
		<p>If Scoring Job completes successfully, we will also send the Scoring Job's Summary email to <strong><%= @autoscoring_project_scoring_job.autoscoring_project.project_manager.email %></strong></p>
	</div>
</div>
<% end %>


<% if @autoscoring_project_scoring_job.encountered_errors? ||@autoscoring_project_scoring_job.completed? %>
<div class="row-fluid">
	<div class="span5">
		<h4>Current Auto-Scoring Job's Attempt #<%= @autoscoring_project_scoring_job.number_of_attempts_count %> Details</h4>
		<div class="scoring-job-details-block">
			<p><b>Scoring Job Creator: </b><%= @autoscoring_project_scoring_job.user.name %> (<%= @autoscoring_project_scoring_job.user.email %>)</p>
			<p><b>Input File Name: </b><%= File.basename(@autoscoring_project_scoring_job.autoscoring_project_scoring_job_input_file.file_name.path) %></p>
			<p><b>Scoring Job Creator Notes:</b> <%= @autoscoring_project_scoring_job.details %></p>
			<% if @autoscoring_project_scoring_job_log %>
			<p><b>Input File Row Count:</b> <%= @autoscoring_project_scoring_job_log.row_count %></p>
			<p><b>Rows Filtered Out:</b> <%=  @autoscoring_project_scoring_job_log.rows_filtered_out %></p>
			<p><b>Inclusion Rate (Scored Rows / Input File Row Count):</b> 
			<% if !@autoscoring_project_scoring_job_log.row_count.blank? %> 
				<%= number_to_percentage( @autoscoring_project_scoring_job_log.row_inclusion_percentage, :precision => 2) %> of the records are included in completed output file based on the Auto-Scoring Project's Filter Criteria</p>
			<% else %>
			File row count is 0 or N/A so inclusion rate cannot be calculated.
			<% end %>
			<p><b>Input File Column Count:</b> <%=  @autoscoring_project_scoring_job_log.column_count %></p>
				<p><b>Processing Time:</b> <%=  @autoscoring_project_scoring_job.processing_time_approximate %> /  <%=  @autoscoring_project_scoring_job.processing_time_exact %></p>
			<% end %>
		</div>
	</div>
	<div class="span5">
		<div class="scoring-job-details-block">
			<% if @autoscoring_project_scoring_job_log %>
			<h4>Processing Details From Last Scoring Job</h4>
			<p><b>Filter Criteria Configured:</b> <%= raw RedCloth.new(@autoscoring_project_scoring_job_log.filter_criteria).to_html if @autoscoring_project_scoring_job_log.filter_criteria.present?%></p>
			<p><b>Conversion Criteria Configured:</b> <%= raw RedCloth.new(@autoscoring_project_scoring_job_log.conversion_criteria).to_html if @autoscoring_project_scoring_job_log.conversion_criteria.present? %></p>
			<p><b>Date Last Processed:</b> <%=  @autoscoring_project_scoring_job_log.created_at.strftime("%m/%d/%y %I:%M %p %Z") %></p>
			<p><b>Split Output By Column Configured:</b> <%= @autoscoring_project_scoring_job_log.split_output_by_column_name %></p>
			<% if @autoscoring_project_scoring_job.encountered_errors? %>
			<h4  class="text-error"><i class="icon-search icon-remove"></i> Error Details From Last Scoring Job</h4>
			<%= raw RedCloth.new(@autoscoring_project_scoring_job_log.error_details).to_html if @autoscoring_project_scoring_job_log.error_details.present? %>
			<% end %>
			<% end %>
		</div>
	</div>
</div>
<% end %>

<div class="row-fluid">
	<div class="span10">
			<% if Rails.env.development? || Rails.env.test? %>
				<%= link_to '<i class="icon-refresh"></i> PREVIEW EMAIL - FOR DEV'.html_safe, preview_email_autoscoring_project_scoring_job_path(@autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-primary" %>
				<%= link_to '<i class="icon-refresh"></i> Admin - PROCESS - FOR DEV'.html_safe, process_file_autoscoring_project_scoring_job_path(@autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-primary" %>
			<% end %>
			<% if current_user.is_administrator? %>
				<%= link_to '<i class="icon-refresh"></i> Admin - Create Output CSV File'.html_safe, create_output_csv_file_autoscoring_project_scoring_job_path(@autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-primary" %>
				<%= link_to ' <i class="icon-warning-refresh"></i>  Admin - Sidekiq Enqueue Scoring Jobs Input File'.html_safe, enqueue_file_on_sidekiq_autoscoring_project_scoring_job_path(@autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-primary" %>
					<%=  link_to ' <i class="icon-download-alt"></i> Admin - Download Attempted File'.html_safe, download_current_input_file_autoscoring_project_scoring_job_path(@autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-primary" %>
			<% end %>
	
			<% if @autoscoring_project_scoring_job.completed? %>
			<h4><%=  @autoscoring_project_scoring_job.autoscoring_project_scoring_job_output_files.count.to_s %> Scored CSV File(s)</h4>	
			
				<div class="alert alert-block alert-info">
						<% if @autoscoring_project_scoring_job.has_multiple_output_files? %>
					This Scoring Job contains <strong>multiple</strong> CSV output files available to download because it records were split prior to scoring by their value in the column '<%= @autoscoring_project_scoring_job_log.split_output_by_column_name %>'.
						<% else %>
							This Scoring Job has only one CSV output file.
						<% end %>
				</div>
			
				<table class="table table-hover">
					<thead>
					<tr>
						<th>Group</th>
						<th class="scored-csv-file-file-name">File Name</th>
						<th>Actions</th>
					</tr>
					</thead>
					<tbody>
						<%  @autoscoring_project_scoring_job.autoscoring_project_scoring_job_output_files.each do |output_file| %>
						<tr>
							<td><%= @autoscoring_project_scoring_job.has_multiple_output_files? ? output_file.split_value : "All Records" %></td>
							<td><%= File.basename(output_file.file_name.url, ".csv") %></td>
							<td><%= link_to '<i class="icon-download-alt"></i> Download'.html_safe, download_csv_output_file_autoscoring_project_scoring_job_path(:output_file_id => output_file), :class => "btn btn-large btn-block btn-success" %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
			
			<% if @autoscoring_project_scoring_job.encountered_errors? %>
					<p><%=  link_to ' <i class="icon-download-alt"></i> Download Attempted File'.html_safe, download_current_input_file_autoscoring_project_scoring_job_path( @autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-primary" %></p>	
				<p><%= link_to  '<i class="icon-upload"></i> Upload Revised File'.html_safe, edit_autoscoring_project_scoring_job_path(@autoscoring_project_scoring_job), :class => "btn btn-large btn-block btn-warning" %></p>
			<% end %>
	</div>
</div>