config/routes.rb
RcEnrollmentSystem::Application.routes.draw do

  resources :autoscoring_project_scoring_jobs do
    member do
      get 'process_file'
      get 'queued_process_file'
      get 'download_current_input_file'
      get 'create_dbf_file'
      get 'create_output_csv_file'
      get 'download_dbf_file'
      get 'download_csv_input_file'
      get 'download_csv_output_file'
      get 'enqueue_file_on_resque'
      get 'enqueue_file_on_sidekiq'
      get 'preview_email'
      get 'delete_scoring_job_records'
    end
  end

  resources :postal_codes do
    collection do
      get 'autocomplete_search'
    end
  end

  resources :job_titles

  resources :autoscoring_project_other_variables

  resources :autoscoring_project_other_variable_count_imports

  resources :autoscoring_project_geodemographic_variable_count_imports

  resources :autoscoring_projects

  resources :institutions

  resources :file_imports do
    member do
      get 'test_import'
      get 'import'
      get 'download'
    end
  end

  devise_for :users

  resources :users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :admin_users do
    member do
      get 'reset_password'
      get 'invite'
    end
  end

  root :to => 'home#index'

  authenticate :admin_user do
    mount Resque::Server.new, :at => "/resque"
  end

  authenticate :admin_user do
    mount Sidekiq::Web.new, at: '/sidekiq'
  end

end

app/views/layouts/_footer.html.erb
<footer>

</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% cache do %>
<%= link_to image_tag("ruffalocody-grey.png"), root_path, :class => 'brand' %></li>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
</a>
<% end %>
<div class="nav-collapse collapse">
	<ul class="nav pull-left">
	<li></li>
	</ul>
	<ul class="nav pull-right">
		<% if user_signed_in? %>
		<% if current_user.is_administrator? %>
		<li>
		<%= link_to('Admin Panel', admin_root_path) %>
		</li>
		<% end %>
		<% end %>
		
	  	<% if user_signed_in? %>
	    <li>
	    <%= link_to('Manage Account', edit_user_registration_path(current_user)) %>
	    </li>
	    <li>
	    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
	    </li>
		<% else %>
		 <li>
			<%= link_to "Sign in", new_session_path(resource_name) %>
		</li>
		<% end %>
	</ul>
	</div>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
	<div class="well sidebar-nav">
		<ul class="nav nav-list">
			<li><%= link_to "Home", root_path %></li>
		</ul>
	</div>
	<div class="well sidebar">
		<h5>Technical Help</h5>
		<p>
			Please contact<br />
			<a href="mailto:brian@austengroup.com">Brian Kasen</a>
		</p>
	</div>
<% else %>
<% end %>
<% if params[:controller] == "pages" %>
<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RuffaloCODY EM Auto-Score System</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-top">
		<nav class="navbar-inner">
			<div class="container-fluid">
				<%= render 'layouts/navigation' %>
			</div>
		</nav>
	</header>
	<div class="container-fluid">  
		<div class="row-fluid">
			<div id="flash" class="span12">
				<%= render 'layouts/messages' %>
			</div>
		</div>
		<div class="row-fluid">
				
				
			<% if user_signed_in? %>
				<div class="span2">
					<%= render 'layouts/sidebar' %>
				</div>
				<div class="span10">
					<%= yield %>
				</div>
			<% else %>
				<div class="span12">
					<%= yield %>
				</div>
			<% end %>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</div>
</body>
</html>